<?php

namespace App\Models\Invoicing;

class TaxDocumentTypes 
{
    const FACTURA = 30;
    const FACTURA_DE_VENTAS_Y_SERVICIOS_NO_AFECTOS_O_EXENTOS_DE_IVA = 32;
    const FACTURA_ELECTRONICA = 33;
    const FACTURA_NO_AFECTA_O_EXENTA_ELECTRONICA = 34;
    const BOLETA = 35;
    const BOLETA_EXENTA = 38;
    const BOLETA_ELECTRONICA = 39;
    const LIQUIDACION_FACTURA = 40;
    const BOLETA_EXENTA_ELECTRONICA = 41;
    const LIQUIDACION_FACTURA_ELECTRONICA = 43;
    const FACTURA_DE_COMPRA = 45;
    const FACTURA_DE_COMPRA_ELECTRONICA = 46;
    const PAGO_ELECTRONICO = 48;
    const GUIA_DE_DESPACHO = 50;
    const GUIA_DE_DESPACHO_ELECTRONICA = 52;
    const NOTA_DE_DEBITO = 55;
    const NOTA_DE_DEBITO_ELECTRONICA = 56;
    const NOTA_DE_CREDITO = 60;
    const NOTA_DE_CREDITO_ELECTRONICA = 61;
    const LIQUIDACION = 103;
    const FACTURA_DE_EXPORTACION_ELECTRONICA = 110;
    const NOTA_DE_DEBITO_DE_EXPORTACION_ELECTRONICA = 111;
    const NOTA_DE_CREDITO_DE_EXPORTACION_ELECTRONICA = 112;
}
