<?php

use Illuminate\Database\Seeder;

class ExerciseStagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('exercise_stages')->delete();
        
        \DB::table('exercise_stages')->insert(array (
            0 => 
            array (
                'id' => 1,
                'exercise_id' => 15,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 1,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'exercise_id' => 17,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 1,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'exercise_id' => 14,
                'stage_id' => 2,
                'weight' => '',
                'time' => 0,
                'repetitions' => 6,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'exercise_id' => 5,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 1,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'exercise_id' => 29,
                'stage_id' => 2,
                'weight' => '',
                'time' => 0,
                'repetitions' => 6,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'exercise_id' => 26,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 3,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'exercise_id' => 13,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 2,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'exercise_id' => 8,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 1,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'exercise_id' => 27,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 5,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'exercise_id' => 5,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 6,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'exercise_id' => 4,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 3,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'exercise_id' => 20,
                'stage_id' => 2,
                'weight' => '',
                'time' => 0,
                'repetitions' => 3,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'exercise_id' => 28,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 6,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'exercise_id' => 24,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 3,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'exercise_id' => 4,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 5,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'exercise_id' => 22,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 3,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'exercise_id' => 6,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 6,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'exercise_id' => 29,
                'stage_id' => 2,
                'weight' => '',
                'time' => 0,
                'repetitions' => 1,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'exercise_id' => 8,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 3,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'exercise_id' => 29,
                'stage_id' => 2,
                'weight' => '',
                'time' => 0,
                'repetitions' => 6,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'exercise_id' => 23,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 1,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'exercise_id' => 28,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 6,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'exercise_id' => 2,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 6,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'exercise_id' => 9,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 3,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'exercise_id' => 23,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 5,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'exercise_id' => 29,
                'stage_id' => 2,
                'weight' => '',
                'time' => 0,
                'repetitions' => 1,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'exercise_id' => 9,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 2,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'exercise_id' => 17,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 5,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'exercise_id' => 8,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 6,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'exercise_id' => 18,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 4,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'exercise_id' => 29,
                'stage_id' => 2,
                'weight' => '',
                'time' => 0,
                'repetitions' => 5,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'exercise_id' => 14,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 6,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'exercise_id' => 4,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 5,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'exercise_id' => 14,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 4,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'exercise_id' => 1,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 2,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'exercise_id' => 29,
                'stage_id' => 2,
                'weight' => '',
                'time' => 0,
                'repetitions' => 5,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'exercise_id' => 22,
                'stage_id' => 2,
                'weight' => '',
                'time' => 0,
                'repetitions' => 5,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'exercise_id' => 12,
                'stage_id' => 2,
                'weight' => '',
                'time' => 0,
                'repetitions' => 2,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'exercise_id' => 15,
                'stage_id' => 2,
                'weight' => '',
                'time' => 0,
                'repetitions' => 4,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'exercise_id' => 28,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 4,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'exercise_id' => 19,
                'stage_id' => 2,
                'weight' => '',
                'time' => 0,
                'repetitions' => 4,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'exercise_id' => 15,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 5,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'exercise_id' => 15,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 3,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'exercise_id' => 24,
                'stage_id' => 2,
                'weight' => '',
                'time' => 0,
                'repetitions' => 3,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'exercise_id' => 20,
                'stage_id' => 2,
                'weight' => '',
                'time' => 0,
                'repetitions' => 2,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'exercise_id' => 20,
                'stage_id' => 2,
                'weight' => '',
                'time' => 0,
                'repetitions' => 2,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'exercise_id' => 1,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 6,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'exercise_id' => 27,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 3,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'exercise_id' => 23,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 4,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'exercise_id' => 30,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 1,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'exercise_id' => 17,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 5,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'exercise_id' => 20,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 1,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'exercise_id' => 26,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 2,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'exercise_id' => 17,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 4,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'exercise_id' => 26,
                'stage_id' => 2,
                'weight' => '',
                'time' => 0,
                'repetitions' => 1,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'exercise_id' => 6,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 1,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'exercise_id' => 4,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 4,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'exercise_id' => 18,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 3,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'exercise_id' => 18,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 5,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'exercise_id' => 11,
                'stage_id' => 2,
                'weight' => '',
                'time' => 0,
                'repetitions' => 2,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'exercise_id' => 13,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 3,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'exercise_id' => 25,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 6,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'exercise_id' => 5,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 5,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'exercise_id' => 26,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 3,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'exercise_id' => 2,
                'stage_id' => 2,
                'weight' => '',
                'time' => 0,
                'repetitions' => 2,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'exercise_id' => 27,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 3,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'exercise_id' => 11,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 3,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'exercise_id' => 22,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 5,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'exercise_id' => 10,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 3,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'exercise_id' => 10,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 1,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'exercise_id' => 9,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 4,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'exercise_id' => 12,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 4,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'exercise_id' => 3,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 2,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'exercise_id' => 26,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 5,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'exercise_id' => 15,
                'stage_id' => 2,
                'weight' => '',
                'time' => 0,
                'repetitions' => 1,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'exercise_id' => 22,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 1,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'exercise_id' => 5,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 1,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'exercise_id' => 2,
                'stage_id' => 2,
                'weight' => '',
                'time' => 0,
                'repetitions' => 6,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'exercise_id' => 28,
                'stage_id' => 2,
                'weight' => '',
                'time' => 0,
                'repetitions' => 3,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'exercise_id' => 20,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 5,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'exercise_id' => 5,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 6,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'exercise_id' => 3,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 4,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'exercise_id' => 4,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 5,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'exercise_id' => 1,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 6,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'exercise_id' => 8,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 6,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'exercise_id' => 18,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 4,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'exercise_id' => 10,
                'stage_id' => 2,
                'weight' => '',
                'time' => 0,
                'repetitions' => 3,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'exercise_id' => 15,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 2,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'exercise_id' => 30,
                'stage_id' => 2,
                'weight' => '',
                'time' => 0,
                'repetitions' => 6,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'exercise_id' => 4,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 6,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'exercise_id' => 25,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 2,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'exercise_id' => 11,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 2,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'exercise_id' => 28,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 6,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'exercise_id' => 14,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 4,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'exercise_id' => 5,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 5,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'exercise_id' => 9,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 5,
                'round' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'exercise_id' => 23,
                'stage_id' => 1,
                'weight' => '',
                'time' => 0,
                'repetitions' => 6,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'exercise_id' => 27,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 4,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'exercise_id' => 15,
                'stage_id' => 2,
                'weight' => '',
                'time' => 0,
                'repetitions' => 3,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'exercise_id' => 3,
                'stage_id' => 3,
                'weight' => '',
                'time' => 0,
                'repetitions' => 2,
                'round' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}